import { NextFunction, Request, Response } from "express"
import createHttpError from "http-errors"
import users from "../../services/user"
import { differenceInYears } from "date-fns/fp"
import db from "../../connectors/knex.connector"
